franka_description:
  ubuntu:
  - ros-lyrical-franka-description
franka_lock_unlock:
  ubuntu:
  - ros-lyrical-franka-lock-unlock
franka_msgs:
  ubuntu:
  - ros-lyrical-franka-msgs
integration_launch_testing:
  ubuntu:
  - ros-lyrical-integration-launch-testing
libfranka:
  ubuntu:
  - ros-lyrical-libfranka
librealsense2:
  ubuntu:
  - ros-lyrical-librealsense2
orbbec_camera_msgs:
  ubuntu:
  - ros-lyrical-orbbec-camera-msgs
orbbec_description:
  ubuntu:
  - ros-lyrical-orbbec-description
realsense2_camera_msgs:
  ubuntu:
  - ros-lyrical-realsense2-camera-msgs
franka_gripper:
  ubuntu:
  - ros-lyrical-franka-gripper
franka_hardware:
  ubuntu:
  - ros-lyrical-franka-hardware
franka_utils:
  ubuntu:
  - ros-lyrical-franka-utils
orbbec_camera:
  ubuntu:
  - ros-lyrical-orbbec-camera
realsense2_camera:
  ubuntu:
  - ros-lyrical-realsense2-camera
realsense2_description:
  ubuntu:
  - ros-lyrical-realsense2-description
franka_moveit_config:
  ubuntu:
  - ros-lyrical-franka-moveit-config
franka_semantic_components:
  ubuntu:
  - ros-lyrical-franka-semantic-components
mul_franka_description:
  ubuntu:
  - ros-lyrical-mul-franka-description
franka_example_controllers:
  ubuntu:
  - ros-lyrical-franka-example-controllers
franka_robot_state_broadcaster:
  ubuntu:
  - ros-lyrical-franka-robot-state-broadcaster
franka_bringup:
  ubuntu:
  - ros-lyrical-franka-bringup
mul_franka_launch:
  ubuntu:
  - ros-lyrical-mul-franka-launch
